# Generated by Django 3.1 on 2020-11-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDBMS_app', '0005_auto_20201130_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='RDBMS_app.Tag'),
        ),
    ]
